### PR TITLE
Temporarily fix OpenStruct with fix for `class` and `method` attributes

### PR DESCRIPTION
**Pull request by marcoroth**
# Type of PR

Temporary fix

## Description

OpenStruct 0.5.2 which comes bundled with Ruby 3.1 has a bug when creating an OpenStruct object with the `class` and `method` attributes in this order.

```ruby
irb(main):003:0> os = OpenStruct.new(class: "my-class", method: "post")
/Users/marcoroth/.anyenv/envs/rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/ostruct-0.5.2/lib/ostruct.rb:249:in `is_method_protected!': undefined method `ancestors' for "my-class":String (NoMethodError)

        self.class.ancestors.any? do |mod|
                  ^^^^^^^^^^
	from /Users/marcoroth/.anyenv/envs/rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/ostruct-0.5.2/lib/ostruct.rb:223:in `new_ostruct_member!'
```

## Why should this be added

Makes StimulusReflex work with Ruby 3.1, or any app that has `openstruct` 0.5.2 bundled with it.

We can remove this fix once ruby/ostruct#37 is merged, released and bundled with the next Ruby version.

Thanks @Laykou!

## Checklist

- [x] My code follows the style guidelines of this project
- [x] Checks (StandardRB & Prettier-Standard) are passing
- [x] This is not a documentation update

### CODE REVIEW

**Review by hopsoft — APPROVED** [review]

**Comment by Laykou** [comment]
btw https://github.com/ruby/ostruct/pull/37 is already merged and new ostruct version released under 0.5.3
